main_app/urls.py
from django.urls import path
from . import views
from .views import get_unavailable_dates


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('terms/', views.terms, name='terms'),
    path('products/', views.ProductList.as_view(), name='product_list'),
    path('products/<int:pk>', views.ProductDetail.as_view(), name='product_detail'),
    path('products/<int:pk>/rent_product/', views.rent_product, name='rent_product'),
    path('products/create/', views.ProductCreate.as_view(), name='product_create'),
    path('products/<int:pk>/update', views.ProductUpdate.as_view(), name='product_update'),
    path('products/<int:pk>/delete', views.ProductDelete.as_view(), name='product_delete'),
    path('products/<int:pk>/review', views.ReviewCreate.as_view(), name='review_create'),
    # path('products/<int:pk>/add_image', views.add_image, name='add_image'),
    path('get_unavailable_dates/<int:product_id>/', get_unavailable_dates, name='get_unavailable_dates'),
    ## accounts Root
    path('accounts/profile/<str:username>/detail', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('accounts/profile/<str:username>/', views.Profile.as_view(), name='profile' ),
    path('accounts/profile/<str:username>/dashboard/', views.ProfileDashboard.as_view(), name='profile_dashboard'),
    path('accounts/profile/<str:username>/update/', views.ProfileUpdate.as_view(), name='profile_update'),
    path('accounts/register/', views.register, name='register'),
]

renthub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.contrib.auth import get_user_model
from datetime import datetime
# Create your models here...
# User = get_user_model()


RATINGS = (
    ('5', 'Execellent'),
    ('4', 'Very good'),
    ('3', 'Ok'),
    ('2', 'Bad'),
    ('1', 'Very bad'),
)


class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        # Create normal user Email Require
        if not email:
            raise ValueError('The Email field must be set')
        # else:
        email = self.normalize_email(email)

        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)

        user.save(using=self._db)
        return user
    
        # Create superuser user, password, email
    def create_superuser(self, email, username, password=None, **extra_fields):
        
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, username, password, **extra_fields)
    

# User Model
class CustomUser(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    avatar = models.URLField(max_length=200)
    address = models.CharField(
        verbose_name='Address',max_length=150, null=True, blank=True
        )
    town = models.CharField(
        verbose_name='Town/City',max_length=150, null=True, blank=True
        )
    county = models.CharField(
        verbose_name='County',max_length=150, null=True, blank=True
        )
    post_code = models.CharField(
        verbose_name='Post Code',max_length=150, null=True, blank=True
        )
    country = models.CharField(
        verbose_name='Country',max_length=150, null=True, blank=True
        )
    # >>>>> add user fixing admin user error <<<<<
    user = models.CharField(max_length=255)
    #
    # location = models.PointField(null=True, blank=True)
    #
    objects = CustomUserManager()

    def __str__(self):
        return self.username
    
    def get_absolute_url(self):
        return reverse('profile-detail', kwargs={'pk': self.id})

# Category Model
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'pk': self.id})


# Product Model
class Product(models.Model):
    product_name = models.CharField(max_length=50)
    description = models.TextField(max_length=255)
    price = models.PositiveIntegerField()
    # many to many Category
    category = models.ManyToManyField(Category)
    # one to many User
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    

    def __str__(self):
        return f'{self.product_name} ({self.id})'

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_id': self.id})
    
    # get average rating to show on product
    def get_average(self):
        reviews = self.review_set.all()
        average_rating = sum([float(review.rating) for review in reviews]) / self.review_set.count()
        return round(average_rating, 2)
    
    def is_available(self, date_rent, date_return):
        all_rentings = Renting.objects.filter(product=self)
        for renting in all_rentings:
            if renting.date_rent <= date_return and renting.date_return >= date_rent:
                return False
        return True
    
    def total_price(self, date_rent, date_return):
        delta = date_return - date_rent
        total_days = delta.days
        total_price = round(total_days * self.price, 2)
        return total_price

# Image Model
class Image(models.Model):
    image = models.ImageField(upload_to='product_images')
    # one to many Product
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"Image for product_id: {self.product_id} @{self.image}"


# Review Model
class Review(models.Model):
    date = models.DateField('Review Date')
    description = models.TextField(max_length=255)
    rating = models.CharField(
        max_length=20,
        choices=RATINGS,
        default=RATINGS[0][0]
    )
    # one to many Product
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    # one to many User
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.user} review: {self.product} {self.rating}'
    
    class Meta:
        ordering = ['-date']


# Renting Model
class Renting(models.Model):
    date_rent = models.DateField('Renting Date')
    date_return = models.DateField('Return Date')
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    # one to many Product
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # one to many User
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return  f'{self.user.username} {self.product} ({self.date_rent}) - ({self.date_return}), Total Price: {self.total_price}'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'renting_id': self.id})
    
    class Meta:
        ordering = ['-date_rent']

main_app/views.py
from typing import Any
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, get_user_model
from .forms import CustomUserCreationForm, ReviewForm, RentingForm, ImageUploadForm, ImageFormSet, UpdateProfileForm
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View, TemplateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product, Image, Renting, Category, CustomUser, Review
from main_app.templatetags.user_dashboard import user_products, user_rent
from django.utils import timezone
from django.db.models import Q
from django.db.models import Sum
from django.http import JsonResponse
from datetime import datetime, timedelta

import os
import boto3
import uuid
from pprint import pprint

# retrieves the user model active
User = get_user_model()

# path('about', views.about, name='about'),
# path('products', views.product_index, name='index'),
# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html' )

def terms(request):
    return render(request, 'terms.html')

# Leave a review
class ReviewCreate(LoginRequiredMixin, View):
    def get(self, request, pk):
# instantiating Review Form Class and passing the form to be rendered
        form = ReviewForm()
        context = {'form': form}
        return render(request, 'review_form.html', context)
# take all the information provided in the form, validates and creates a review in Review model.
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        if form.is_valid():
            date = form.cleaned_data['date']
            rating = form.cleaned_data['rating']
            description = form.cleaned_data['description']
            product = Product.objects.get(pk=pk)
            user_reviews = Review.objects.filter(user=request.user, product=product)
            if user_reviews.exists():
                messages.error(request, 'You have already left a review for this listing.')
                return redirect('review_create', pk=pk)
            elif product.user == request.user:
                messages.error(request, 'You cannot leave a review for your own listing.')
                return redirect('review_create', pk=pk)
            else:
                review = Review.objects.create(
                    date=date,
                    rating=rating,
                    description=description,
                    user=request.user,
                    product_id=pk
                )
                review.save()
                messages.success(request, 'Thank you for your review!')
                return redirect('review_create', pk=pk)
        else:
            messages.error(request, 'Error. Please try again.')
        context = {'form': form}
        return render(request, 'review_form.html', context)

# Profile Detail (LoginRequiredMixin)
class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'profile/profile_detail.html'
    context_object_name = 'profile'

#  Prevent other users from accessing profiles that do not belong to them.
    def get_object(self, queryset=None):
        # Get the requested profile or raise a 404 error if not found
        profile = get_object_or_404(User, username=self.kwargs['username'])
        print('User: ', User)
        # Check if the authenticated user is owner  profile
        # profile.user != self.request.user
        print(self.request.user)
        if profile != self.request.user:
            print('profile: ', profile)
            print('self.request.user: ', self.request.user)
            # return PermissionDenied("permission Denied to views profile.")
            raise PermissionDenied("permission Denied to views profile.")
        print('Profile: ', profile)

        return profile
    
# Profile Edit (LoginRequiredMixin)
class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = CustomUser
    template_name = 'profile/profile_form.html'
    form_class = UpdateProfileForm
    success_url = reverse_lazy('profile_detail')

    def get_object(self, queryset=None):
        username = self.kwargs['username']
        user = get_object_or_404(CustomUser, username=username)
        if user != self.request.user:
            raise PermissionDenied("Permission Denied to update profile.")
        return user
    
    # Redirect to detail page
    # https://docs.djangoproject.com/en/5.0/ref/urlresolvers/#reverse-lazy
    def get_success_url(self):
        return reverse_lazy('profile_detail', kwargs={'username': self.object.username})

    
# Profile Dashboard (LoginRequiredMixin)
class Profile(LoginRequiredMixin, TemplateView):
    template_name = 'profile/profile.html'

    def get(self, request, username):
        user = User.objects.get(username=username)
        products = user_products(user)
        rent = user_rent(user)
        now = timezone.now()
        product_ids = products.values_list('id', flat=True)
        # rented_product_ids = Renting.objects.filter(product_id=product_ids)
        rented_product_ids = Renting.objects.filter(product__id__in=product_ids).values_list('product__id', flat=True)

        total_products = Product.objects.filter(user=user).count()
        total_rentings = Renting.objects.filter(product__in=products).count()
        context = {
            'user': user,
            'products': products,
            'rent': rent,
            'now': now,
            'rented_product_ids': rented_product_ids,
            'total_products': total_products,
            'total_rentings': total_rentings
            }
        return render(request, self.template_name, context)


# Profile Dashboard (LoginRequiredMixin)
class ProfileDashboard(LoginRequiredMixin, TemplateView):
    template_name = 'profile/profile_dashboard.html'
    def get(self, request, username):
        
        print('User:', username)
        if username != request.user.username:
            raise PermissionDenied("Permission to access this page.")
        user = User.objects.get(username=username)
        products = user_products(user)
        rent = user_rent(user)
        now = timezone.now()
        product_ids = products.values_list('id', flat=True)
        # rented_product_ids = Renting.objects.filter(product_id=product_ids)
        rented_product_ids = Renting.objects.filter(product__id__in=product_ids).values_list('product__id', flat=True)
        # filter Renting by 
        total_rentings = Renting.objects.filter(product__in=products).count()
        latest_renting = Renting.objects.filter(product__in=products).last()
        # latest_renting = Renting.objects.filter(product__in=products).order_by('-date_rent').first()
        current_user = request.user
        print('user ', user)
        print('current_user ', current_user)
        # Calculate total outcome from the current user's rented products
        
        total_outcome = 0
        rent_out_filter = Renting.objects.filter(user=current_user)
        for renting in rent_out_filter:
            total_outcome += renting.total_price
        
        total_income = 0
        rent_in_filter = Renting.objects.filter(product__in=products)
        for renting in rent_in_filter:
            total_income += renting.total_price

        # Total Balance
        total = total_income - total_outcome
        context = {
            'user': user,
            'products': products,
            'rent': rent,
            'now': now,
            'rented_product_ids': rented_product_ids,
            'total_rentings': total_rentings,
            'latest_renting': latest_renting,
            'total_income': total_income,
            'total_outcome': total_outcome,
            'total': total
            }
        return render(request, self.template_name, context)

# @transaction.atomic block unSucceeds create user to database
@transaction.atomic
def register(request):
    error_message = ''

    if request.method == 'POST':  
        form = CustomUserCreationForm(request.POST)  
        if form.is_valid():  
            form.save()
            # if user successful redirect to home page
            return redirect('login')
        else:
            # if not show error message or read error in terminal >> print(form.errors)
            print(form.errors)
            error_message = 'Invalid sign up - try again'
    else:
        form = CustomUserCreationForm()   

    context = {  
        'form':form,
        'error_message': error_message  
    }  
    return render(request, 'registration/signup.html', context)  

class ProductList(LoginRequiredMixin, ListView):
    paginate_by = 9
    model = Product
    template_name = 'main_app/product_list.html'

    # to display the categories
    def get_queryset(self):
        queryset = super().get_queryset()
        categories_filter = self.request.GET.getlist('categories-filter')
        min_value = self.request.GET.get('min')
        max_value = self.request.GET.get('max')
        search = self.request.GET.get('query')

# ------------- FILTER BY -------------------- #
        
        if min_value == '' or min_value is None:
            min_value = 0
        if max_value == '' or max_value is None:
            max_value = 100000
   
        if len(categories_filter) != 0:
            queryset = queryset.filter(category__name__in=categories_filter)
            if min_value != 0 or max_value != 100000:
                queryset = queryset.filter(Q(price__gte=min_value)& Q(price__lte=max_value))
        elif min_value != 0 or max_value != 100000:
            queryset = queryset.filter(Q(price__gte=min_value)& Q(price__lte=max_value))

main_app/templates/profile/profile.html
{% extends '../base.html' %}
{% load user_dashboard %}

{% block title %} Profile | RentHub {% endblock %}

{% block content %}


<div class="container mt-4">
    <div class="row">
        <div class="col-md-3 mt-4">
            <nav class="navbar navbar-light bg-light">
                <div class="container-fluid">
                    <div class="row">
                        <!-- ########################## -->
                        <nav id="sidebar" class="col bg-light sidebar">
                            <div class="position-sticky">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'profile_dashboard' username=request.user.username %}"
                                            class="nav-link active" aria-current="page">
                                            <i data-feather="home"></i>
                                            <span class="ml-2">Dashboard</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'profile' username=request.user.username %}" class="nav-link"
                                            aria-current="page">
                                            <i data-feather="user"></i>
                                            <span class="ml-2">Profile</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'profile_update' username=request.user.username %}" class="nav-link"
                                            aria-current="page">
                                            <i data-feather="users"></i>
                                            <span class="ml-2">Update Details</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'profile_detail' username=request.user.username %}" class="nav-link" aria-current="page">
                                            <i data-feather="zoom-in"></i>
                                            <span class="ml-2">Account Details</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'product_list' %}" class="nav-link" aria-current="page">
                                            <i data-feather="shopping-cart"></i>
                                            <span class="ml-2">Products</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'product_create' %}" class="nav-link" aria-current="page">
                                            <i data-feather="plus-square"></i>
                                            <span class="ml-2">Add Product</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <form method="post" action="{% url 'logout' %}">
                                            {% csrf_token %}
                                            <button class="btn btn-link p-0 nav-link"><div class="" style="padding: 8px 16px;"><i data-feather="log-out" class="logout"></i> Log Out</div></button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </nav>
        </div>
        <!-- examples Profile -->
        <!-- https://mdbootstrap.com/docs/standard/extended/profiles/ -->
        <div class="col-md-9">
            <div class="col-md-12 my-4">
                <div class="card" style="border-radius: 15px;">
                    <div class="rounded-top text-white d-flex flex-row" style="background-color: #6D6FFE; height:200px;">
                        <div class="ms-4 mt-5 d-flex flex-column" style="width: 152px;">
                            {% if user.avatar %}
                                <img src="{{ user.avatar }}" alt="{{ user.username }} Avatar" class="object-fit-cover  img-fluid img-thumbnail mt-4 mb-2" style="height: 152px; z-index: 1;">
                            {% else %}
                                <img src="https://img.freepik.com/free-psd/3d-illustration-person-with-sunglasses_23-2149436188.jpg?w=2000&t=st=1707500967~exp=1707501567~hmac=694b42c585124522d023577f39f2b191b77eb2c44366e75c36d1a52c2e8a0064" alt="support avatar" class="object-fit-cover  img-fluid img-thumbnail mt-4 mb-2" style="height: 152px; z-index: 1">
                            {% endif %}
                            <button type="button" class="btn btn-outline-dark" data-mdb-ripple-color="dark" style="z-index: 1;">{{ user.username }}</button>
                        </div>
                        <div class="ms-3" style="margin-top: 133px;">
                            {% if user.first_name %}
                                <h5>{{ user.first_name }} {{ user.last_name }}</h5>
                            {% else %}
                                <h5>Alfa Jupiter</h5>
                            {% endif %}
                            {% if user.country %}
                                <p>{{ user.country }}</p>
                            {% else %}
                                <p>Interstellar Space</p>
                            {% endif %}
                        </div>
                    </div>
                    <div class="p-4 text-black" style="background-color: #ffffff;">
                        <div class="d-flex justify-content-end text-center py-1">
                            <div>
                                <p class="mb-1 h5">{{ total_products }}</p>
                                <p class="small text-muted mb-0">Products</p>
                            </div>
                            <div class="px-3">
                                <p class="mb-1 h5">{{ total_rentings }}</p>
                                <p class="small text-muted mb-0">Rental Frequency</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-flex pt-1">
                <button type="button" class="btn btn-primary flex-grow-1">My Listings</button>
                <button type="button" class="btn btn-outline-primary me-1 flex-grow-1">Message</button>
            </div>
            <h3 class="my-4">My Listings</h2>
            <div class="row row-cols-1 row-cols-md-2 g-3">
                {% user_products user as products %}
                {% for product in products %}
                <div class="col">
                    <div class="card">
                        {% if product.image_set.first.image %}
                        <img src="{{ product.image_set.first.image.url }}" class="card-img object-fit-cover" alt="{{ product.product_name }}" style="height: 300px; width: 100%;">
                        {% else %}
                        <img src="https://www.svgrepo.com/show/508699/landscape-placeholder.svg" class="card-img object-fit-cover" alt="{{ product.product_name }}" style="height: 300px; width: 100%;">
                        {% endif %}
                        <div class="card-img-overlay d-flex align-content-between justify-content-between">
                            <h5 class="card-title text-white">{{ product.product_name }}</h5>
                            <div class="d-flex flex-column align-self-end">
                                <a href="{% url 'product_detail' product.id %}" class="btn btn-primary rounded-pill my-2">Details</a>
                            {% if product.id in rented_product_ids %}
                                {% if now|date:"Y-m-d" < product.renting_set.last.date_return|date:"Y-m-d" and now|date:"Y-m-d" < product.renting_set.last.date_rent|date:"Y-m-d" %} 
                                    <span class="badge" style="background-color: #f7b832; color: #ffffff; width: 75.59px;">Booked</span>
                                {% elif now|date:"Y-m-d" <= product.renting_set.first.date_return|date:"Y-m-d" %} 
                                    <span class="badge" style="background-color: #f76d32; color: #ffffff; width: 75.59px;">Rented</span>
                                {% elif now|date:"Y-m-d" > product.renting_set.last.date_return|date:"Y-m-d" %}
                                    <span class="badge" style="background-color: #15d22e; color: #ffffff; width: 75.59px;">Available</span>
                                {% endif %}
                            {% else %}
                                <span class="badge" style="background-color: #15d22e; color: #ffffff; width: 75.59px;">Available</span>
                            {% endif %}
                            </div>   
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="card mt-4">
                <div class="card-body">
                    <h3>Renting History</h3>
                    <table id="history-table" class="table">
                        <thead>
                            <tr>
                                <th scope="col">Product Name</th>
                                <th scope="col">Pickup Date</th>
                                <th scope="col">Return Date</th>
                                <th scope="col">Total Price</th>
                                <th scope="col">Booking Status</th>
                                <th scope="col">Review Status</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% user_rent user as rentings %}
                        {% for renting in rentings %}
                            <tr>
                                <td><a href="{% url 'product_detail' renting.product.pk %}">{{ renting.product.product_name }}</a></td>
                                <td>{{ renting.date_rent }}</td>
                                <td>{{ renting.date_return }}</td>
                                <td>${{ renting.total_price }}</td>
                                {% comment %} Booking Status {% endcomment %}
                                {% if now|date:"Y-m-d" < renting.date_return|date:"Y-m-d" and now|date:"Y-m-d" < renting.date_rent|date:"Y-m-d" %}
                                    <td><span class="badge" style="background-color: #f7b832; color: #ffffff; width: 75.59px;">Reserved</span></td>
                                {% elif now|date:"Y-m-d" >= renting.date_return|date:"Y-m-d" %}
                                    <td><span class="badge" style="background-color: #f76d32; color: #ffffff; width: 75.59px;">Returned</span></td>
                                {% else %}
                                    <td><span class="badge" style="background-color: #15d22e; color: #ffffff; width: 75.59px;">Ongoing</span></td>
                                {% endif %}
                                {% comment %} Review Status {% endcomment %}
                                {% if renting.product.review_set.exists %}
                                    <td><span class="badge" style="background-color: #15d22e; color: #ffffff;">Review Left</span></td>
                                {% elif now|date:"Y-m-d" >= renting.date_return|date:"Y-m-d" %}
                                    <td><a href="{% url 'review_create' pk=renting.product.pk %}"><span class="badge" style="background-color: #f7b832; color: #ffffff;">Leave Review</span></a></td>
                                {% else %}
                                    <td><i data-feather="x" style="height: 20px;"></i></td>
                                {% endif %}
                            </tr>
                                {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}